# Generated by Django 4.1.4 on 2022-12-24 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='salt',
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='token',
            field=models.UUIDField(default=uuid.UUID('a6e82fa5-5704-4457-99ac-7d88fba06d5c'), editable=False),
        ),
    ]
