# Generated by Django 4.1.4 on 2022-12-24 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_registrationrequest_salt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrequest',
            old_name='allowed',
            new_name='allow',
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='token',
            field=models.UUIDField(default=uuid.UUID('e5d6d3d6-21d0-441d-8e8b-646ecb604fc8'), editable=False),
        ),
    ]
